### PR TITLE
extend example to allow for user input for server address

### PR DESCRIPTION
**Pull request by ultrasaurus**
Submitting for review and feedback,,,

In retrospect, the example was much easier to understand
with hard-coded strings.  Or maybe I just don't know how to use `URI::builder` to make the
code more readable. Creating a string from the IP address and then calling URI::try_from
would be more concise (and maybe ok for this simply case), but I'd like to figure out a pattern
that would be good for all the requests.

This may be better as a separate example (perhaps extended to vary the kinds of requests it makes).  Though maybe you want less example code while the library is still in early development.

### CODE REVIEW

**Comment by sgodwincs** [comment]
Perhaps it's better if the user just supplies the entire URI when running the example?

E.g. `cargo run --example client rtsp://127.0.0.1/`

That way you can just do `URI::try_from(...)` on it and avoid having to deal with the different URI components.

**Comment by ultrasaurus** [comment]
By observation (see below for an example), I noticed that some RTSP requests commonly seem to include a port and some don't... though maybe it would be fine to always include the port.  In the [spec](https://tools.ietf.org/html/rfc2326), section 3.2 documents that the port is optional so if it were always present, I suppose it would be fine.  The code would certainly be nicer if that works.  I will test it out to see if it seems to work in the wild.

VLC player connecting to ip camera:
```
Source       Destination  Length Info
10.0.0.210   10.0.0.8     189    OPTIONS rtsp://10.0.0.8:554/title.dsp RTSP/1.0
10.0.0.8     10.0.0.210   193    Reply: RTSP/1.0 200 OK
10.0.0.210   10.0.0.8     215    DESCRIBE rtsp://10.0.0.8:554/title.dsp RTSP/1.0
10.0.0.8     10.0.0.210   526    Reply: RTSP/1.0 200 OK
10.0.0.210   10.0.0.8     235    SETUP rtsp://10.0.0.8/trackID=0 RTSP/1.0
10.0.0.8     10.0.0.210   343    Reply: RTSP/1.0 200 OK
10.0.0.210   10.0.0.8     218    PLAY rtsp://10.0.0.8 RTSP/1.0
10.0.0.8     10.0.0.210   303    Reply: RTSP/1.0 200 OK
10.0.0.210   10.0.0.8     203    TEARDOWN rtsp://10.0.0.8 RTSP/1.0
10.0.0.8     10.0.0.210   235    Reply: RTSP/1.0 200 OK
```

**Comment by sgodwincs** [comment]
The port is definitely optional in the requests, and this implementation has no problem with that. The problem is with the `Client::connect` function which takes a `SocketAddr`. A `SocketAddr` requires a port to be set.

It might be worth switching it to take just a URI instead and then extract the authority from it to create a `SocketAddr`. This does contain unnecessary path, query, etc. information and we'd probably want to verify that the scheme is correct, but it may be better ergonomically.

**Comment by ultrasaurus** [comment]
this PR is replaced by:  https://github.com/sgodwincs/rtsp-rs/pull/36

**Pull request closed without merging**
